name: Memer Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
        DOCKER_IMAGE_ORIGIN: "docker.pkg.github.com/nickosh/memer/memer"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build . --file Dockerfile -t ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA}
    - name: Docker login
      run: docker login docker.pkg.github.com -u publisher -p "${GITHUB_TOKEN}"
    - name: Tag latest image
      run: docker tag ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA} ${DOCKER_IMAGE_ORIGIN}:latest
    - name: Push current
      run: docker push ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA}
    - name: Push latest
      run: docker push ${DOCKER_IMAGE_ORIGIN}:latest
