name: Memer Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_ORIGIN: "docker.pkg.github.com/nickosh/memer/memer"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build . --file Dockerfile --no-cache -t ${DOCKER_IMAGE_ORIGIN}:$(echo ${GITHUB_SHA} | cut -c1-8)
      - name: Docker login
        run: docker login docker.pkg.github.com -u publisher -p "${GITHUB_TOKEN}"
      - name: Push
        run: docker push ${DOCKER_IMAGE_ORIGIN}:$(echo ${GITHUB_SHA} | cut -c1-8)
