name: Memer Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build . --file Dockerfile -t ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_IMAGE_ORIGIN: "docker.pkg.github.com/nickosh/memer/memer"
    - name: Docker login
      run: docker login docker.pkg.github.com -u publisher -p "${GITHUB_TOKEN}"
    - name: Push
      run:
        docker tag ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA} ${DOCKER_IMAGE_ORIGIN}:latest
        docker push ${DOCKER_IMAGE_ORIGIN}:${GITHUB_SHA}
        docker push ${DOCKER_IMAGE_ORIGIN}:latest
